# spring.application.name 설정을 주석 해제하여 사용
spring.application.name: board1
debug: true  # debug 모드 활성화

# server 포트 설정
server:
  port: 8080

# 데이터베이스 연결 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_codingrecipe1?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user_codingrecipe1
    password: 1234
# MyBatis 설정
mybatis:
  mapper-locations: classpath:**/*.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.codingrecipe1.board1.domain

    #logging:
    #level:
  # root: TRACE  # 전체 로그를 TRACE 레벨로 설정
